export type OrcaFabricaTable = {
  name: string;
  use: string;
  columns: Array<{ name: string; type: "string" | "number" | "date"; use: string }>;
};

const text = (name: string, use: string) => ({ name, type: "string" as const, use });
const number = (name: string, use: string) => ({ name, type: "number" as const, use });
const date = (name: string, use: string) => ({ name, type: "date" as const, use });

/**
 * Business-only analytics catalog. Authentication, authorization, sessions,
 * passkeys, devices, logs, notifications, and secret/identity columns are
 * deliberately excluded. The widget queries only the columns registered here.
 */
export const ORCA_FABRICA_BUSINESS_TABLES: OrcaFabricaTable[] = [
  {
    name: "branches",
    use: "One row is a company depot or operating branch.",
    columns: [
      text("id", "Unique branch identifier."),
      text("branch_name", "Depot display name."),
      text("branch_type", "Operational branch classification."),
      text("city", "Branch city."),
      text("state", "Branch state."),
      text("pin_code", "Branch postal code."),
      date("created_at", "When the branch record was created."),
    ],
  },
  {
    name: "company",
    use: "One row contains the logistics company's business profile.",
    columns: [
      text("id", "Unique company identifier."),
      text("company_name", "Company display name."),
      text("legal_business_name", "Registered legal name."),
      text("company_type", "Legal organization type."),
      text("industry", "Company industry."),
      text("city", "Registered city."),
      text("state", "Registered state."),
      text("country", "Registered country."),
    ],
  },
  {
    name: "contracts",
    use: "One row is a customer logistics contract and its recurring commercial terms.",
    columns: [
      text("id", "Unique contract identifier."),
      text("contract_name", "Contract display name."),
      text("company_name", "Customer company name."),
      text("company_type", "Customer company type."),
      text("city", "Customer city."),
      text("state", "Customer state."),
      number("fixed_monthly_charge", "Recurring monthly contract charge in INR."),
      number("fixed_yearly_charge", "Recurring yearly contract charge in INR."),
      date("created_at", "When the contract was created."),
    ],
  },
  {
    name: "contract_entries",
    use: "One row is a route or pricing rule belonging to a customer contract.",
    columns: [
      text("id", "Unique pricing-rule identifier."),
      text("contract_id", "Contract that owns the rule."),
      text("from_location_id", "Origin location identifier."),
      text("to_location_id", "Destination location identifier."),
      text("from_pin_code", "Origin postal code."),
      text("to_pin_code", "Destination postal code."),
      number("per_manifest_amount", "Charge per manifest in INR."),
      number("monthly_change_amount", "Additional monthly amount in INR."),
      number("yearly_change_amount", "Additional yearly amount in INR."),
      date("created_at", "When the pricing rule was created."),
    ],
  },
  {
    name: "locations",
    use: "One row is an origin, destination, or operating location used by trips and contracts.",
    columns: [
      text("id", "Unique location identifier."),
      text("location_name", "Location display name."),
      text("location_type", "Operational location category."),
      text("city", "Location city."),
      text("district", "Location district."),
      text("state", "Location state."),
      text("country", "Location country."),
      text("pin_code", "Location postal code."),
    ],
  },
  {
    name: "departments",
    use: "One row is an internal operating department used to organize company resources.",
    columns: [
      text("id", "Unique department identifier."),
      text("name", "Department display name."),
      text("code", "Short internal department code."),
      text("description", "Business purpose of the department."),
      date("created_at", "When the department was created."),
    ],
  },
  {
    name: "vehicles",
    use: "One row is a company vehicle available for logistics operations.",
    columns: [
      text("id", "Unique vehicle identifier."),
      text("branch_id", "Branch responsible for the vehicle."),
      text("registration_number", "Government vehicle registration number."),
      text("internal_code", "Internal fleet code."),
      text("manufacturer", "Vehicle manufacturer."),
      text("model", "Vehicle model."),
      text("fuel_type", "Vehicle fuel type."),
      number("payload_capacity_kg", "Maximum payload in kilograms."),
      number("purchase_cost", "Vehicle purchase cost in INR."),
      date("purchase_date", "Vehicle purchase date."),
      number("year_of_manufacture", "Vehicle manufacturing year."),
    ],
  },
  {
    name: "drivers",
    use: "One row is an operational driver; private identity, banking, address, and document fields are excluded.",
    columns: [
      text("id", "Unique driver identifier."),
      text("branch_id", "Driver's assigned branch."),
      text("driver_code", "Internal driver code."),
      text("full_name", "Driver display name."),
      text("licence_type", "Driving licence category."),
      date("licence_expiry_date", "Driving licence expiry date."),
      date("joining_date", "Employment start date."),
      date("ending_date", "Employment end date when applicable."),
      text("salary_type", "Driver salary calculation type."),
      number("salary_amount", "Configured salary amount in INR."),
    ],
  },
  {
    name: "transporters",
    use: "One row is a hired transport company; banking, tax, address, and contact details are excluded.",
    columns: [
      text("id", "Unique transporter identifier."),
      text("branch_id", "Branch responsible for the transporter."),
      text("transporter_name", "Transporter display name."),
      text("transporter_type", "Transporter business category."),
      text("legal_business_name", "Registered transporter name."),
      text("city", "Transporter city."),
      text("state", "Transporter state."),
      date("created_at", "When the transporter was created."),
    ],
  },
  {
    name: "trips",
    use: "One row is a currently open logistics trip.",
    columns: [
      text("id", "Unique trip identifier."),
      text("trip_code", "Unique business trip code."),
      text("branch_id", "Branch responsible for the trip."),
      text("contract_id", "Customer contract used by the trip."),
      text("vehicle_id", "Assigned vehicle identifier."),
      text("driver_id", "Assigned driver identifier."),
      text("transporter_id", "Hired transporter identifier when applicable."),
      text("ownership", "Whether the trip uses an owned or hired vehicle."),
      date("start_date", "Trip start date."),
      date("end_date", "Planned trip end date."),
      number("odometer_start", "Odometer at trip start."),
      number("odometer_end", "Odometer at trip end."),
    ],
  },
  {
    name: "closed_trips",
    use: "One row is a completed logistics trip with final financial totals.",
    columns: [
      text("id", "Unique archived trip identifier."),
      text("trip_code", "Unique business trip code."),
      text("branch_id", "Branch responsible for the trip."),
      text("branch_name", "Branch display name at closure."),
      date("start_date", "Trip start date."),
      date("end_date", "Trip end date."),
      date("closed_at", "When the trip was finalized."),
      number("total_income", "Total trip income in INR."),
      number("total_expense", "Total trip expense in INR."),
      number("net_income", "Final trip profit or loss in INR."),
    ],
  },
  {
    name: "trip_manifests",
    use: "One row is a shipment manifest carried on a trip.",
    columns: [
      text("id", "Unique manifest identifier."),
      text("trip_id", "Trip carrying the manifest."),
      text("manifest_number", "Business manifest number."),
      text("from_location_id", "Origin location identifier."),
      text("to_location_id", "Destination location identifier."),
      text("from_pin_code", "Origin postal code."),
      text("to_pin_code", "Destination postal code."),
      number("quantity", "Number of shipment units."),
      number("weight_kg", "Shipment weight in kilograms."),
      date("created_at", "When the manifest was entered."),
    ],
  },
  {
    name: "trip_expenses",
    use: "One row is an individual expense recorded against an open trip.",
    columns: [
      text("id", "Unique trip-expense identifier."),
      text("trip_id", "Trip that incurred the expense."),
      text("expense_name", "Expense category or name."),
      number("amount", "Expense amount in INR."),
      text("note", "Optional business note."),
      date("created_at", "When the expense was recorded."),
    ],
  },
  {
    name: "trip_other_income",
    use: "One row is additional income recorded against an open trip.",
    columns: [
      text("id", "Unique income identifier."),
      text("trip_id", "Trip that earned the income."),
      text("income_name", "Income category or name."),
      number("amount", "Income amount in INR."),
      text("note", "Optional business note."),
      date("created_at", "When the income was recorded."),
    ],
  },
  {
    name: "incomes",
    use: "One row is non-trip business income assigned to a branch or entity.",
    columns: [
      text("id", "Unique income identifier."),
      text("branch_id", "Branch receiving the income."),
      text("income_name", "Income category or description."),
      number("amount", "Income amount in INR."),
      date("entry_date", "Accounting entry date."),
      text("vehicle_id", "Related vehicle when applicable."),
      text("driver_id", "Related driver when applicable."),
      text("transporter_id", "Related transporter when applicable."),
      text("is_received", "Whether payment has been received."),
      date("received_date", "Payment receipt date."),
    ],
  },
  {
    name: "expenditures",
    use: "One row is a non-trip business expenditure assigned to a branch or entity.",
    columns: [
      text("id", "Unique expenditure identifier."),
      text("branch_id", "Branch incurring the expenditure."),
      text("expenditure_name", "Expense category or description."),
      number("amount", "Expense amount in INR."),
      date("entry_date", "Accounting entry date."),
      text("vehicle_id", "Related vehicle when applicable."),
      text("driver_id", "Related driver when applicable."),
      text("transporter_id", "Related transporter when applicable."),
      text("is_paid", "Whether the expense has been paid."),
      date("paid_date", "Payment date."),
    ],
  },
  {
    name: "fastag_transactions",
    use: "One row is a FASTag recharge or toll transaction for a vehicle.",
    columns: [
      text("id", "Unique FASTag transaction identifier."),
      text("vehicle_id", "Vehicle associated with the transaction."),
      text("trip_code", "Related trip code when applicable."),
      text("transaction_type", "Recharge or toll transaction type."),
      number("amount", "Transaction amount in INR."),
      date("transaction_date", "Transaction date."),
      text("note", "Optional business note."),
    ],
  },
  {
    name: "vehicle_insurance",
    use: "One row is a vehicle insurance coverage period and premium.",
    columns: [
      text("id", "Unique insurance record identifier."),
      text("vehicle_id", "Covered vehicle identifier."),
      date("start_date", "Coverage start date."),
      date("end_date", "Coverage expiry date."),
      number("total_amount", "Insurance premium in INR."),
      text("insurance_number", "Insurance policy number."),
    ],
  },
  {
    name: "vehicle_road_tax",
    use: "One row is a vehicle road-tax coverage period and payment.",
    columns: [
      text("id", "Unique road-tax record identifier."),
      text("vehicle_id", "Taxed vehicle identifier."),
      date("start_date", "Road-tax period start date."),
      date("end_date", "Road-tax expiry date."),
      number("total_amount", "Road-tax amount in INR."),
      text("state", "State receiving the road tax."),
    ],
  },
  {
    name: "driver_advances",
    use: "One row is a salary advance issued to a driver.",
    columns: [
      text("id", "Unique advance identifier."),
      text("driver_id", "Driver receiving the advance."),
      text("branch_id", "Branch issuing the advance."),
      number("amount", "Original advance amount in INR."),
      number("remaining_balance", "Advance balance still recoverable in INR."),
      number("monthly_deduction", "Planned monthly recovery in INR."),
      date("payment_date", "Date the advance was paid."),
    ],
  },
  {
    name: "driver_advance_deductions",
    use: "One row is a payroll deduction applied against a driver advance.",
    columns: [
      text("id", "Unique deduction identifier."),
      text("advance_id", "Advance being recovered."),
      text("driver_id", "Driver whose payroll was deducted."),
      text("payroll_id", "Related payroll identifier."),
      date("month", "Payroll month."),
      number("deduction_amount", "Deduction amount in INR."),
      text("is_applied", "Whether the deduction was applied."),
    ],
  },
  {
    name: "driver_payrolls",
    use: "One row is a driver's payroll calculation for a month.",
    columns: [
      text("id", "Unique payroll identifier."),
      text("driver_id", "Driver being paid."),
      text("branch_id", "Payroll branch."),
      date("month", "Payroll month."),
      number("salary_amount", "Gross salary in INR."),
      number("advance_deduction", "Advance recovered in INR."),
      number("net_amount", "Net payroll amount in INR."),
      text("is_paid", "Whether payroll has been paid."),
      date("paid_date", "Payroll payment date."),
    ],
  },
  {
    name: "emi_schedules",
    use: "One row is a vehicle loan and EMI schedule.",
    columns: [
      text("id", "Unique EMI schedule identifier."),
      text("vehicle_id", "Financed vehicle identifier."),
      text("branch_id", "Branch responsible for the loan."),
      number("loan_amount", "Original loan amount in INR."),
      number("purchase_amount", "Vehicle purchase amount in INR."),
      number("down_payment", "Down payment in INR."),
      text("emi_type", "EMI calculation type."),
      number("interest_rate", "Annual interest rate percentage."),
      number("tenure_months", "Loan tenure in months."),
      date("start_date", "EMI schedule start date."),
      text("lender_name", "Lending institution."),
      text("status", "Current loan status."),
    ],
  },
  {
    name: "emi_installments",
    use: "One row is an installment in a vehicle EMI schedule.",
    columns: [
      text("id", "Unique installment identifier."),
      text("schedule_id", "Parent EMI schedule."),
      number("installment_number", "Installment sequence number."),
      date("due_date", "Installment due date."),
      number("amount", "Installment amount in INR."),
      number("principal", "Principal component in INR."),
      number("interest", "Interest component in INR."),
      text("is_paid", "Whether the installment is paid."),
      date("paid_date", "Installment payment date."),
    ],
  },
  {
    name: "yearly_fixed_expenses",
    use: "One row is a recurring yearly business or vehicle expense schedule.",
    columns: [
      text("id", "Unique yearly expense identifier."),
      text("expense_name", "Expense category or name."),
      text("branch_id", "Branch responsible for the expense."),
      text("vehicle_id", "Related vehicle when applicable."),
      number("total_amount", "Yearly total in INR."),
      number("monthly_amount", "Monthly allocation in INR."),
      date("start_date", "Expense schedule start date."),
      date("end_date", "Expense schedule end date."),
      text("status", "Current schedule status."),
    ],
  },
  {
    name: "vehicle_trip_logs",
    use: "One row summarizes fuel, parking, and odometer values for a vehicle on a completed trip.",
    columns: [
      text("id", "Unique vehicle-trip log identifier."),
      text("trip_code", "Related completed trip code."),
      text("vehicle_id", "Vehicle used by the trip."),
      date("trip_date", "Trip accounting date."),
      number("fuel_expense", "Trip fuel expense in INR."),
      number("parking_charges", "Trip parking expense in INR."),
      number("odometer_start", "Odometer reading at trip start."),
      number("odometer_end", "Odometer reading at trip end."),
    ],
  },
  {
    name: "driver_expense_logs",
    use: "One row summarizes driver allowances and time-based expenses for a completed trip.",
    columns: [
      text("id", "Unique driver-expense log identifier."),
      text("trip_code", "Related completed trip code."),
      text("driver_id", "Driver assigned to the trip."),
      date("trip_date", "Trip accounting date."),
      number("driver_bata", "Driver bata allowance in INR."),
      number("morning_exp", "Morning allowance in INR."),
      number("night_exp", "Night allowance in INR."),
    ],
  },
  {
    name: "other_expense_logs",
    use: "One row summarizes miscellaneous operational expenses for a completed trip.",
    columns: [
      text("id", "Unique other-expense log identifier."),
      text("trip_code", "Related completed trip code."),
      date("trip_date", "Trip accounting date."),
      number("dala_charges", "Dala charges in INR."),
      number("unloading", "Unloading charges in INR."),
      number("sunday_exp", "Sunday expense in INR."),
      number("other_amount", "Total additional miscellaneous expense in INR."),
    ],
  },
  {
    name: "approval_charge_advances",
    use: "One row contains the transporter approval-charge advance and remaining balance for a trip.",
    columns: [
      text("id", "Unique approval-charge record identifier."),
      text("trip_id", "Trip associated with the approval charge."),
      text("transporter_id", "Transporter receiving the advance."),
      number("advance", "Advance already paid in INR."),
      number("balance", "Approval-charge balance in INR."),
      date("created_at", "When the approval-charge record was created."),
    ],
  },
  {
    name: "monthly_mis_activities",
    use: "One row is an active or retired Monthly MIS activity configured for a branch.",
    columns: [
      text("id", "Unique MIS activity identifier."),
      text("branch_id", "Branch that owns the activity."),
      text("activity_name", "MIS compliance activity name."),
      text("schedule_type", "Daily, weekly, or day-of-month schedule type."),
      number("schedule_value", "Weekday or month-day value when required."),
      number("sort_order", "Display order within the form."),
      text("is_active", "Whether the activity is currently used."),
      date("created_at", "When the activity was created."),
    ],
  },
  {
    name: "monthly_mis_instances",
    use: "One row is a branch Monthly MIS draft or immutable submitted month; snapshot content is intentionally excluded.",
    columns: [
      text("id", "Unique Monthly MIS instance identifier."),
      text("branch_id", "Branch completing the MIS."),
      date("mis_month", "Month represented by the MIS."),
      text("status", "Draft or submitted status."),
      date("submitted_at", "Final submission time."),
      date("created_at", "When the monthly record was created."),
      date("updated_at", "When the draft was last updated."),
    ],
  },
];
