[mega]
type = mega
user = sparrowaisolutions@gmail.com
pass = d3FItCZ258bnTTG3v4nCghk1neJKVQeI3oAt3F0
session_id = x9rNQ_c2Z8wcAXUmihX6-W5sQ2w2SFplRzVvTQMymdfryOk_muYc5DSmYw
master_key = R+3xdGDI/TgzLOBna6zwdQ==

