/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as MastersRouteImport } from './routes/masters'
import { Route as ImportTripsRouteImport } from './routes/import-trips'
import { Route as HrDashboardRouteImport } from './routes/hr-dashboard'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayrollIndexRouteImport } from './routes/payroll.index'
import { Route as EmployeesIndexRouteImport } from './routes/employees.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AttendanceIndexRouteImport } from './routes/attendance.index'
import { Route as SettingsAttendanceModuleRouteImport } from './routes/settings.attendance-module'
import { Route as PayrollPendingRouteImport } from './routes/payroll.pending'
import { Route as PayrollLoansRouteImport } from './routes/payroll.loans'
import { Route as PayrollLedgerRouteImport } from './routes/payroll.ledger'
import { Route as PayrollHistoryRouteImport } from './routes/payroll.history'
import { Route as PayrollGenerateRouteImport } from './routes/payroll.generate'
import { Route as PayrollDeductionsRouteImport } from './routes/payroll.deductions'
import { Route as PayrollAdvancesRouteImport } from './routes/payroll.advances'
import { Route as EmployeesNewRouteImport } from './routes/employees.new'
import { Route as EmployeesDepartmentsRouteImport } from './routes/employees.departments'
import { Route as DashboardPayrollRouteImport } from './routes/dashboard.payroll'
import { Route as DashboardHierarchyRouteImport } from './routes/dashboard.hierarchy'
import { Route as DashboardEmployeeRouteImport } from './routes/dashboard.employee'
import { Route as DashboardAttendanceRouteImport } from './routes/dashboard.attendance'
import { Route as AttendanceMarkRouteImport } from './routes/attendance.mark'
import { Route as AttendanceHolidaysRouteImport } from './routes/attendance.holidays'
import { Route as AttendanceHistoryRouteImport } from './routes/attendance.history'
import { Route as AttendanceAutomarkerRouteImport } from './routes/attendance.automarker'
import { Route as ApiNotifyOpenTripsRouteImport } from './routes/api/notify-open-trips'
import { Route as ApiNotifyExpiryRouteImport } from './routes/api/notify-expiry'
import { Route as ApiNotifyAdminRouteImport } from './routes/api/notify-admin'
import { Route as EmployeesDepartmentsIndexRouteImport } from './routes/employees.departments.index'
import { Route as EmployeesIdIndexRouteImport } from './routes/employees.$id.index'
import { Route as AttendanceHistoryIndexRouteImport } from './routes/attendance.history.index'
import { Route as EmployeesDepartmentsNewRouteImport } from './routes/employees.departments.new'
import { Route as EmployeesIdEditRouteImport } from './routes/employees.$id.edit'
import { Route as AttendanceHistoryIdRouteImport } from './routes/attendance.history.$id'
import { Route as ApiDriverThemeRouteImport } from './routes/api/driver/theme'
import { Route as EmployeesDepartmentsIdIndexRouteImport } from './routes/employees.departments.$id.index'
import { Route as EmployeesDepartmentsIdEditRouteImport } from './routes/employees.departments.$id.edit'
import { Route as ApiDriverTripsLocationRouteImport } from './routes/api/driver/trips/location'
import { Route as ApiDriverTripsEndRouteImport } from './routes/api/driver/trips/end'
import { Route as ApiDriverTripsCurrentRouteImport } from './routes/api/driver/trips/current'
import { Route as ApiDriverTripsClaimRouteImport } from './routes/api/driver/trips/claim'
import { Route as ApiDriverTripsCheckpointsVerifyRouteImport } from './routes/api/driver/trips/checkpoints/verify'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersRoute = MastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportTripsRoute = ImportTripsRouteImport.update({
  id: '/import-trips',
  path: '/import-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const HrDashboardRoute = HrDashboardRouteImport.update({
  id: '/hr-dashboard',
  path: '/hr-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollIndexRoute = PayrollIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PayrollRoute,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeesRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AttendanceIndexRoute = AttendanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AttendanceRoute,
} as any)
const SettingsAttendanceModuleRoute =
  SettingsAttendanceModuleRouteImport.update({
    id: '/attendance-module',
    path: '/attendance-module',
    getParentRoute: () => SettingsRoute,
  } as any)
const PayrollPendingRoute = PayrollPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => PayrollRoute,
} as any)
const PayrollLoansRoute = PayrollLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => PayrollRoute,
} as any)
const PayrollLedgerRoute = PayrollLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => PayrollRoute,
} as any)
const PayrollHistoryRoute = PayrollHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PayrollRoute,
} as any)
const PayrollGenerateRoute = PayrollGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => PayrollRoute,
} as any)
const PayrollDeductionsRoute = PayrollDeductionsRouteImport.update({
  id: '/deductions',
  path: '/deductions',
  getParentRoute: () => PayrollRoute,
} as any)
const PayrollAdvancesRoute = PayrollAdvancesRouteImport.update({
  id: '/advances',
  path: '/advances',
  getParentRoute: () => PayrollRoute,
} as any)
const EmployeesNewRoute = EmployeesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesDepartmentsRoute = EmployeesDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => EmployeesRoute,
} as any)
const DashboardPayrollRoute = DashboardPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHierarchyRoute = DashboardHierarchyRouteImport.update({
  id: '/hierarchy',
  path: '/hierarchy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmployeeRoute = DashboardEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAttendanceRoute = DashboardAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DashboardRoute,
} as any)
const AttendanceMarkRoute = AttendanceMarkRouteImport.update({
  id: '/mark',
  path: '/mark',
  getParentRoute: () => AttendanceRoute,
} as any)
const AttendanceHolidaysRoute = AttendanceHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => AttendanceRoute,
} as any)
const AttendanceHistoryRoute = AttendanceHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AttendanceRoute,
} as any)
const AttendanceAutomarkerRoute = AttendanceAutomarkerRouteImport.update({
  id: '/automarker',
  path: '/automarker',
  getParentRoute: () => AttendanceRoute,
} as any)
const ApiNotifyOpenTripsRoute = ApiNotifyOpenTripsRouteImport.update({
  id: '/api/notify-open-trips',
  path: '/api/notify-open-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyExpiryRoute = ApiNotifyExpiryRouteImport.update({
  id: '/api/notify-expiry',
  path: '/api/notify-expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyAdminRoute = ApiNotifyAdminRouteImport.update({
  id: '/api/notify-admin',
  path: '/api/notify-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesDepartmentsIndexRoute =
  EmployeesDepartmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EmployeesDepartmentsRoute,
  } as any)
const EmployeesIdIndexRoute = EmployeesIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => EmployeesRoute,
} as any)
const AttendanceHistoryIndexRoute = AttendanceHistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AttendanceHistoryRoute,
} as any)
const EmployeesDepartmentsNewRoute = EmployeesDepartmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EmployeesDepartmentsRoute,
} as any)
const EmployeesIdEditRoute = EmployeesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => EmployeesRoute,
} as any)
const AttendanceHistoryIdRoute = AttendanceHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AttendanceHistoryRoute,
} as any)
const ApiDriverThemeRoute = ApiDriverThemeRouteImport.update({
  id: '/api/driver/theme',
  path: '/api/driver/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesDepartmentsIdIndexRoute =
  EmployeesDepartmentsIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => EmployeesDepartmentsRoute,
  } as any)
const EmployeesDepartmentsIdEditRoute =
  EmployeesDepartmentsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => EmployeesDepartmentsRoute,
  } as any)
const ApiDriverTripsLocationRoute = ApiDriverTripsLocationRouteImport.update({
  id: '/api/driver/trips/location',
  path: '/api/driver/trips/location',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriverTripsEndRoute = ApiDriverTripsEndRouteImport.update({
  id: '/api/driver/trips/end',
  path: '/api/driver/trips/end',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriverTripsCurrentRoute = ApiDriverTripsCurrentRouteImport.update({
  id: '/api/driver/trips/current',
  path: '/api/driver/trips/current',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriverTripsClaimRoute = ApiDriverTripsClaimRouteImport.update({
  id: '/api/driver/trips/claim',
  path: '/api/driver/trips/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriverTripsCheckpointsVerifyRoute =
  ApiDriverTripsCheckpointsVerifyRouteImport.update({
    id: '/api/driver/trips/checkpoints/verify',
    path: '/api/driver/trips/checkpoints/verify',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/employees': typeof EmployeesRouteWithChildren
  '/home': typeof HomeRoute
  '/hr-dashboard': typeof HrDashboardRoute
  '/import-trips': typeof ImportTripsRoute
  '/masters': typeof MastersRoute
  '/operations': typeof OperationsRoute
  '/payroll': typeof PayrollRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/system': typeof SystemRoute
  '/users': typeof UsersRoute
  '/api/notify-admin': typeof ApiNotifyAdminRoute
  '/api/notify-expiry': typeof ApiNotifyExpiryRoute
  '/api/notify-open-trips': typeof ApiNotifyOpenTripsRoute
  '/attendance/automarker': typeof AttendanceAutomarkerRoute
  '/attendance/history': typeof AttendanceHistoryRouteWithChildren
  '/attendance/holidays': typeof AttendanceHolidaysRoute
  '/attendance/mark': typeof AttendanceMarkRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/employee': typeof DashboardEmployeeRoute
  '/dashboard/hierarchy': typeof DashboardHierarchyRoute
  '/dashboard/payroll': typeof DashboardPayrollRoute
  '/employees/departments': typeof EmployeesDepartmentsRouteWithChildren
  '/employees/new': typeof EmployeesNewRoute
  '/payroll/advances': typeof PayrollAdvancesRoute
  '/payroll/deductions': typeof PayrollDeductionsRoute
  '/payroll/generate': typeof PayrollGenerateRoute
  '/payroll/history': typeof PayrollHistoryRoute
  '/payroll/ledger': typeof PayrollLedgerRoute
  '/payroll/loans': typeof PayrollLoansRoute
  '/payroll/pending': typeof PayrollPendingRoute
  '/settings/attendance-module': typeof SettingsAttendanceModuleRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/api/driver/theme': typeof ApiDriverThemeRoute
  '/attendance/history/$id': typeof AttendanceHistoryIdRoute
  '/employees/$id/edit': typeof EmployeesIdEditRoute
  '/employees/departments/new': typeof EmployeesDepartmentsNewRoute
  '/attendance/history/': typeof AttendanceHistoryIndexRoute
  '/employees/$id/': typeof EmployeesIdIndexRoute
  '/employees/departments/': typeof EmployeesDepartmentsIndexRoute
  '/api/driver/trips/claim': typeof ApiDriverTripsClaimRoute
  '/api/driver/trips/current': typeof ApiDriverTripsCurrentRoute
  '/api/driver/trips/end': typeof ApiDriverTripsEndRoute
  '/api/driver/trips/location': typeof ApiDriverTripsLocationRoute
  '/employees/departments/$id/edit': typeof EmployeesDepartmentsIdEditRoute
  '/employees/departments/$id/': typeof EmployeesDepartmentsIdIndexRoute
  '/api/driver/trips/checkpoints/verify': typeof ApiDriverTripsCheckpointsVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/hr-dashboard': typeof HrDashboardRoute
  '/import-trips': typeof ImportTripsRoute
  '/masters': typeof MastersRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/system': typeof SystemRoute
  '/users': typeof UsersRoute
  '/api/notify-admin': typeof ApiNotifyAdminRoute
  '/api/notify-expiry': typeof ApiNotifyExpiryRoute
  '/api/notify-open-trips': typeof ApiNotifyOpenTripsRoute
  '/attendance/automarker': typeof AttendanceAutomarkerRoute
  '/attendance/holidays': typeof AttendanceHolidaysRoute
  '/attendance/mark': typeof AttendanceMarkRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/employee': typeof DashboardEmployeeRoute
  '/dashboard/hierarchy': typeof DashboardHierarchyRoute
  '/dashboard/payroll': typeof DashboardPayrollRoute
  '/employees/new': typeof EmployeesNewRoute
  '/payroll/advances': typeof PayrollAdvancesRoute
  '/payroll/deductions': typeof PayrollDeductionsRoute
  '/payroll/generate': typeof PayrollGenerateRoute
  '/payroll/history': typeof PayrollHistoryRoute
  '/payroll/ledger': typeof PayrollLedgerRoute
  '/payroll/loans': typeof PayrollLoansRoute
  '/payroll/pending': typeof PayrollPendingRoute
  '/settings/attendance-module': typeof SettingsAttendanceModuleRoute
  '/attendance': typeof AttendanceIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/payroll': typeof PayrollIndexRoute
  '/api/driver/theme': typeof ApiDriverThemeRoute
  '/attendance/history/$id': typeof AttendanceHistoryIdRoute
  '/employees/$id/edit': typeof EmployeesIdEditRoute
  '/employees/departments/new': typeof EmployeesDepartmentsNewRoute
  '/attendance/history': typeof AttendanceHistoryIndexRoute
  '/employees/$id': typeof EmployeesIdIndexRoute
  '/employees/departments': typeof EmployeesDepartmentsIndexRoute
  '/api/driver/trips/claim': typeof ApiDriverTripsClaimRoute
  '/api/driver/trips/current': typeof ApiDriverTripsCurrentRoute
  '/api/driver/trips/end': typeof ApiDriverTripsEndRoute
  '/api/driver/trips/location': typeof ApiDriverTripsLocationRoute
  '/employees/departments/$id/edit': typeof EmployeesDepartmentsIdEditRoute
  '/employees/departments/$id': typeof EmployeesDepartmentsIdIndexRoute
  '/api/driver/trips/checkpoints/verify': typeof ApiDriverTripsCheckpointsVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/employees': typeof EmployeesRouteWithChildren
  '/home': typeof HomeRoute
  '/hr-dashboard': typeof HrDashboardRoute
  '/import-trips': typeof ImportTripsRoute
  '/masters': typeof MastersRoute
  '/operations': typeof OperationsRoute
  '/payroll': typeof PayrollRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/system': typeof SystemRoute
  '/users': typeof UsersRoute
  '/api/notify-admin': typeof ApiNotifyAdminRoute
  '/api/notify-expiry': typeof ApiNotifyExpiryRoute
  '/api/notify-open-trips': typeof ApiNotifyOpenTripsRoute
  '/attendance/automarker': typeof AttendanceAutomarkerRoute
  '/attendance/history': typeof AttendanceHistoryRouteWithChildren
  '/attendance/holidays': typeof AttendanceHolidaysRoute
  '/attendance/mark': typeof AttendanceMarkRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/employee': typeof DashboardEmployeeRoute
  '/dashboard/hierarchy': typeof DashboardHierarchyRoute
  '/dashboard/payroll': typeof DashboardPayrollRoute
  '/employees/departments': typeof EmployeesDepartmentsRouteWithChildren
  '/employees/new': typeof EmployeesNewRoute
  '/payroll/advances': typeof PayrollAdvancesRoute
  '/payroll/deductions': typeof PayrollDeductionsRoute
  '/payroll/generate': typeof PayrollGenerateRoute
  '/payroll/history': typeof PayrollHistoryRoute
  '/payroll/ledger': typeof PayrollLedgerRoute
  '/payroll/loans': typeof PayrollLoansRoute
  '/payroll/pending': typeof PayrollPendingRoute
  '/settings/attendance-module': typeof SettingsAttendanceModuleRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/api/driver/theme': typeof ApiDriverThemeRoute
  '/attendance/history/$id': typeof AttendanceHistoryIdRoute
  '/employees/$id/edit': typeof EmployeesIdEditRoute
  '/employees/departments/new': typeof EmployeesDepartmentsNewRoute
  '/attendance/history/': typeof AttendanceHistoryIndexRoute
  '/employees/$id/': typeof EmployeesIdIndexRoute
  '/employees/departments/': typeof EmployeesDepartmentsIndexRoute
  '/api/driver/trips/claim': typeof ApiDriverTripsClaimRoute
  '/api/driver/trips/current': typeof ApiDriverTripsCurrentRoute
  '/api/driver/trips/end': typeof ApiDriverTripsEndRoute
  '/api/driver/trips/location': typeof ApiDriverTripsLocationRoute
  '/employees/departments/$id/edit': typeof EmployeesDepartmentsIdEditRoute
  '/employees/departments/$id/': typeof EmployeesDepartmentsIdIndexRoute
  '/api/driver/trips/checkpoints/verify': typeof ApiDriverTripsCheckpointsVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/dashboard'
    | '/employees'
    | '/home'
    | '/hr-dashboard'
    | '/import-trips'
    | '/masters'
    | '/operations'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
    | '/system'
    | '/users'
    | '/api/notify-admin'
    | '/api/notify-expiry'
    | '/api/notify-open-trips'
    | '/attendance/automarker'
    | '/attendance/history'
    | '/attendance/holidays'
    | '/attendance/mark'
    | '/dashboard/attendance'
    | '/dashboard/employee'
    | '/dashboard/hierarchy'
    | '/dashboard/payroll'
    | '/employees/departments'
    | '/employees/new'
    | '/payroll/advances'
    | '/payroll/deductions'
    | '/payroll/generate'
    | '/payroll/history'
    | '/payroll/ledger'
    | '/payroll/loans'
    | '/payroll/pending'
    | '/settings/attendance-module'
    | '/attendance/'
    | '/dashboard/'
    | '/employees/'
    | '/payroll/'
    | '/api/driver/theme'
    | '/attendance/history/$id'
    | '/employees/$id/edit'
    | '/employees/departments/new'
    | '/attendance/history/'
    | '/employees/$id/'
    | '/employees/departments/'
    | '/api/driver/trips/claim'
    | '/api/driver/trips/current'
    | '/api/driver/trips/end'
    | '/api/driver/trips/location'
    | '/employees/departments/$id/edit'
    | '/employees/departments/$id/'
    | '/api/driver/trips/checkpoints/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/hr-dashboard'
    | '/import-trips'
    | '/masters'
    | '/operations'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
    | '/system'
    | '/users'
    | '/api/notify-admin'
    | '/api/notify-expiry'
    | '/api/notify-open-trips'
    | '/attendance/automarker'
    | '/attendance/holidays'
    | '/attendance/mark'
    | '/dashboard/attendance'
    | '/dashboard/employee'
    | '/dashboard/hierarchy'
    | '/dashboard/payroll'
    | '/employees/new'
    | '/payroll/advances'
    | '/payroll/deductions'
    | '/payroll/generate'
    | '/payroll/history'
    | '/payroll/ledger'
    | '/payroll/loans'
    | '/payroll/pending'
    | '/settings/attendance-module'
    | '/attendance'
    | '/dashboard'
    | '/employees'
    | '/payroll'
    | '/api/driver/theme'
    | '/attendance/history/$id'
    | '/employees/$id/edit'
    | '/employees/departments/new'
    | '/attendance/history'
    | '/employees/$id'
    | '/employees/departments'
    | '/api/driver/trips/claim'
    | '/api/driver/trips/current'
    | '/api/driver/trips/end'
    | '/api/driver/trips/location'
    | '/employees/departments/$id/edit'
    | '/employees/departments/$id'
    | '/api/driver/trips/checkpoints/verify'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/dashboard'
    | '/employees'
    | '/home'
    | '/hr-dashboard'
    | '/import-trips'
    | '/masters'
    | '/operations'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
    | '/system'
    | '/users'
    | '/api/notify-admin'
    | '/api/notify-expiry'
    | '/api/notify-open-trips'
    | '/attendance/automarker'
    | '/attendance/history'
    | '/attendance/holidays'
    | '/attendance/mark'
    | '/dashboard/attendance'
    | '/dashboard/employee'
    | '/dashboard/hierarchy'
    | '/dashboard/payroll'
    | '/employees/departments'
    | '/employees/new'
    | '/payroll/advances'
    | '/payroll/deductions'
    | '/payroll/generate'
    | '/payroll/history'
    | '/payroll/ledger'
    | '/payroll/loans'
    | '/payroll/pending'
    | '/settings/attendance-module'
    | '/attendance/'
    | '/dashboard/'
    | '/employees/'
    | '/payroll/'
    | '/api/driver/theme'
    | '/attendance/history/$id'
    | '/employees/$id/edit'
    | '/employees/departments/new'
    | '/attendance/history/'
    | '/employees/$id/'
    | '/employees/departments/'
    | '/api/driver/trips/claim'
    | '/api/driver/trips/current'
    | '/api/driver/trips/end'
    | '/api/driver/trips/location'
    | '/employees/departments/$id/edit'
    | '/employees/departments/$id/'
    | '/api/driver/trips/checkpoints/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  EmployeesRoute: typeof EmployeesRouteWithChildren
  HomeRoute: typeof HomeRoute
  HrDashboardRoute: typeof HrDashboardRoute
  ImportTripsRoute: typeof ImportTripsRoute
  MastersRoute: typeof MastersRoute
  OperationsRoute: typeof OperationsRoute
  PayrollRoute: typeof PayrollRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SystemRoute: typeof SystemRoute
  UsersRoute: typeof UsersRoute
  ApiNotifyAdminRoute: typeof ApiNotifyAdminRoute
  ApiNotifyExpiryRoute: typeof ApiNotifyExpiryRoute
  ApiNotifyOpenTripsRoute: typeof ApiNotifyOpenTripsRoute
  ApiDriverThemeRoute: typeof ApiDriverThemeRoute
  ApiDriverTripsClaimRoute: typeof ApiDriverTripsClaimRoute
  ApiDriverTripsCurrentRoute: typeof ApiDriverTripsCurrentRoute
  ApiDriverTripsEndRoute: typeof ApiDriverTripsEndRoute
  ApiDriverTripsLocationRoute: typeof ApiDriverTripsLocationRoute
  ApiDriverTripsCheckpointsVerifyRoute: typeof ApiDriverTripsCheckpointsVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters': {
      id: '/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof MastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-trips': {
      id: '/import-trips'
      path: '/import-trips'
      fullPath: '/import-trips'
      preLoaderRoute: typeof ImportTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-dashboard': {
      id: '/hr-dashboard'
      path: '/hr-dashboard'
      fullPath: '/hr-dashboard'
      preLoaderRoute: typeof HrDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll/': {
      id: '/payroll/'
      path: '/'
      fullPath: '/payroll/'
      preLoaderRoute: typeof PayrollIndexRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/employees/': {
      id: '/employees/'
      path: '/'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/attendance/': {
      id: '/attendance/'
      path: '/'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AttendanceIndexRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/settings/attendance-module': {
      id: '/settings/attendance-module'
      path: '/attendance-module'
      fullPath: '/settings/attendance-module'
      preLoaderRoute: typeof SettingsAttendanceModuleRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/payroll/pending': {
      id: '/payroll/pending'
      path: '/pending'
      fullPath: '/payroll/pending'
      preLoaderRoute: typeof PayrollPendingRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/payroll/loans': {
      id: '/payroll/loans'
      path: '/loans'
      fullPath: '/payroll/loans'
      preLoaderRoute: typeof PayrollLoansRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/payroll/ledger': {
      id: '/payroll/ledger'
      path: '/ledger'
      fullPath: '/payroll/ledger'
      preLoaderRoute: typeof PayrollLedgerRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/payroll/history': {
      id: '/payroll/history'
      path: '/history'
      fullPath: '/payroll/history'
      preLoaderRoute: typeof PayrollHistoryRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/payroll/generate': {
      id: '/payroll/generate'
      path: '/generate'
      fullPath: '/payroll/generate'
      preLoaderRoute: typeof PayrollGenerateRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/payroll/deductions': {
      id: '/payroll/deductions'
      path: '/deductions'
      fullPath: '/payroll/deductions'
      preLoaderRoute: typeof PayrollDeductionsRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/payroll/advances': {
      id: '/payroll/advances'
      path: '/advances'
      fullPath: '/payroll/advances'
      preLoaderRoute: typeof PayrollAdvancesRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/employees/new': {
      id: '/employees/new'
      path: '/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof EmployeesNewRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/departments': {
      id: '/employees/departments'
      path: '/departments'
      fullPath: '/employees/departments'
      preLoaderRoute: typeof EmployeesDepartmentsRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/dashboard/payroll': {
      id: '/dashboard/payroll'
      path: '/payroll'
      fullPath: '/dashboard/payroll'
      preLoaderRoute: typeof DashboardPayrollRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hierarchy': {
      id: '/dashboard/hierarchy'
      path: '/hierarchy'
      fullPath: '/dashboard/hierarchy'
      preLoaderRoute: typeof DashboardHierarchyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employee': {
      id: '/dashboard/employee'
      path: '/employee'
      fullPath: '/dashboard/employee'
      preLoaderRoute: typeof DashboardEmployeeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/attendance': {
      id: '/dashboard/attendance'
      path: '/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof DashboardAttendanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/attendance/mark': {
      id: '/attendance/mark'
      path: '/mark'
      fullPath: '/attendance/mark'
      preLoaderRoute: typeof AttendanceMarkRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/attendance/holidays': {
      id: '/attendance/holidays'
      path: '/holidays'
      fullPath: '/attendance/holidays'
      preLoaderRoute: typeof AttendanceHolidaysRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/attendance/history': {
      id: '/attendance/history'
      path: '/history'
      fullPath: '/attendance/history'
      preLoaderRoute: typeof AttendanceHistoryRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/attendance/automarker': {
      id: '/attendance/automarker'
      path: '/automarker'
      fullPath: '/attendance/automarker'
      preLoaderRoute: typeof AttendanceAutomarkerRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/api/notify-open-trips': {
      id: '/api/notify-open-trips'
      path: '/api/notify-open-trips'
      fullPath: '/api/notify-open-trips'
      preLoaderRoute: typeof ApiNotifyOpenTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-expiry': {
      id: '/api/notify-expiry'
      path: '/api/notify-expiry'
      fullPath: '/api/notify-expiry'
      preLoaderRoute: typeof ApiNotifyExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-admin': {
      id: '/api/notify-admin'
      path: '/api/notify-admin'
      fullPath: '/api/notify-admin'
      preLoaderRoute: typeof ApiNotifyAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/departments/': {
      id: '/employees/departments/'
      path: '/'
      fullPath: '/employees/departments/'
      preLoaderRoute: typeof EmployeesDepartmentsIndexRouteImport
      parentRoute: typeof EmployeesDepartmentsRoute
    }
    '/employees/$id/': {
      id: '/employees/$id/'
      path: '/$id'
      fullPath: '/employees/$id/'
      preLoaderRoute: typeof EmployeesIdIndexRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/attendance/history/': {
      id: '/attendance/history/'
      path: '/'
      fullPath: '/attendance/history/'
      preLoaderRoute: typeof AttendanceHistoryIndexRouteImport
      parentRoute: typeof AttendanceHistoryRoute
    }
    '/employees/departments/new': {
      id: '/employees/departments/new'
      path: '/new'
      fullPath: '/employees/departments/new'
      preLoaderRoute: typeof EmployeesDepartmentsNewRouteImport
      parentRoute: typeof EmployeesDepartmentsRoute
    }
    '/employees/$id/edit': {
      id: '/employees/$id/edit'
      path: '/$id/edit'
      fullPath: '/employees/$id/edit'
      preLoaderRoute: typeof EmployeesIdEditRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/attendance/history/$id': {
      id: '/attendance/history/$id'
      path: '/$id'
      fullPath: '/attendance/history/$id'
      preLoaderRoute: typeof AttendanceHistoryIdRouteImport
      parentRoute: typeof AttendanceHistoryRoute
    }
    '/api/driver/theme': {
      id: '/api/driver/theme'
      path: '/api/driver/theme'
      fullPath: '/api/driver/theme'
      preLoaderRoute: typeof ApiDriverThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/departments/$id/': {
      id: '/employees/departments/$id/'
      path: '/$id'
      fullPath: '/employees/departments/$id/'
      preLoaderRoute: typeof EmployeesDepartmentsIdIndexRouteImport
      parentRoute: typeof EmployeesDepartmentsRoute
    }
    '/employees/departments/$id/edit': {
      id: '/employees/departments/$id/edit'
      path: '/$id/edit'
      fullPath: '/employees/departments/$id/edit'
      preLoaderRoute: typeof EmployeesDepartmentsIdEditRouteImport
      parentRoute: typeof EmployeesDepartmentsRoute
    }
    '/api/driver/trips/location': {
      id: '/api/driver/trips/location'
      path: '/api/driver/trips/location'
      fullPath: '/api/driver/trips/location'
      preLoaderRoute: typeof ApiDriverTripsLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/driver/trips/end': {
      id: '/api/driver/trips/end'
      path: '/api/driver/trips/end'
      fullPath: '/api/driver/trips/end'
      preLoaderRoute: typeof ApiDriverTripsEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/driver/trips/current': {
      id: '/api/driver/trips/current'
      path: '/api/driver/trips/current'
      fullPath: '/api/driver/trips/current'
      preLoaderRoute: typeof ApiDriverTripsCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/driver/trips/claim': {
      id: '/api/driver/trips/claim'
      path: '/api/driver/trips/claim'
      fullPath: '/api/driver/trips/claim'
      preLoaderRoute: typeof ApiDriverTripsClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/driver/trips/checkpoints/verify': {
      id: '/api/driver/trips/checkpoints/verify'
      path: '/api/driver/trips/checkpoints/verify'
      fullPath: '/api/driver/trips/checkpoints/verify'
      preLoaderRoute: typeof ApiDriverTripsCheckpointsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AttendanceHistoryRouteChildren {
  AttendanceHistoryIdRoute: typeof AttendanceHistoryIdRoute
  AttendanceHistoryIndexRoute: typeof AttendanceHistoryIndexRoute
}

const AttendanceHistoryRouteChildren: AttendanceHistoryRouteChildren = {
  AttendanceHistoryIdRoute: AttendanceHistoryIdRoute,
  AttendanceHistoryIndexRoute: AttendanceHistoryIndexRoute,
}

const AttendanceHistoryRouteWithChildren =
  AttendanceHistoryRoute._addFileChildren(AttendanceHistoryRouteChildren)

interface AttendanceRouteChildren {
  AttendanceAutomarkerRoute: typeof AttendanceAutomarkerRoute
  AttendanceHistoryRoute: typeof AttendanceHistoryRouteWithChildren
  AttendanceHolidaysRoute: typeof AttendanceHolidaysRoute
  AttendanceMarkRoute: typeof AttendanceMarkRoute
  AttendanceIndexRoute: typeof AttendanceIndexRoute
}

const AttendanceRouteChildren: AttendanceRouteChildren = {
  AttendanceAutomarkerRoute: AttendanceAutomarkerRoute,
  AttendanceHistoryRoute: AttendanceHistoryRouteWithChildren,
  AttendanceHolidaysRoute: AttendanceHolidaysRoute,
  AttendanceMarkRoute: AttendanceMarkRoute,
  AttendanceIndexRoute: AttendanceIndexRoute,
}

const AttendanceRouteWithChildren = AttendanceRoute._addFileChildren(
  AttendanceRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAttendanceRoute: typeof DashboardAttendanceRoute
  DashboardEmployeeRoute: typeof DashboardEmployeeRoute
  DashboardHierarchyRoute: typeof DashboardHierarchyRoute
  DashboardPayrollRoute: typeof DashboardPayrollRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAttendanceRoute: DashboardAttendanceRoute,
  DashboardEmployeeRoute: DashboardEmployeeRoute,
  DashboardHierarchyRoute: DashboardHierarchyRoute,
  DashboardPayrollRoute: DashboardPayrollRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EmployeesDepartmentsRouteChildren {
  EmployeesDepartmentsNewRoute: typeof EmployeesDepartmentsNewRoute
  EmployeesDepartmentsIndexRoute: typeof EmployeesDepartmentsIndexRoute
  EmployeesDepartmentsIdEditRoute: typeof EmployeesDepartmentsIdEditRoute
  EmployeesDepartmentsIdIndexRoute: typeof EmployeesDepartmentsIdIndexRoute
}

const EmployeesDepartmentsRouteChildren: EmployeesDepartmentsRouteChildren = {
  EmployeesDepartmentsNewRoute: EmployeesDepartmentsNewRoute,
  EmployeesDepartmentsIndexRoute: EmployeesDepartmentsIndexRoute,
  EmployeesDepartmentsIdEditRoute: EmployeesDepartmentsIdEditRoute,
  EmployeesDepartmentsIdIndexRoute: EmployeesDepartmentsIdIndexRoute,
}

const EmployeesDepartmentsRouteWithChildren =
  EmployeesDepartmentsRoute._addFileChildren(EmployeesDepartmentsRouteChildren)

interface EmployeesRouteChildren {
  EmployeesDepartmentsRoute: typeof EmployeesDepartmentsRouteWithChildren
  EmployeesNewRoute: typeof EmployeesNewRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  EmployeesIdEditRoute: typeof EmployeesIdEditRoute
  EmployeesIdIndexRoute: typeof EmployeesIdIndexRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesDepartmentsRoute: EmployeesDepartmentsRouteWithChildren,
  EmployeesNewRoute: EmployeesNewRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  EmployeesIdEditRoute: EmployeesIdEditRoute,
  EmployeesIdIndexRoute: EmployeesIdIndexRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

interface PayrollRouteChildren {
  PayrollAdvancesRoute: typeof PayrollAdvancesRoute
  PayrollDeductionsRoute: typeof PayrollDeductionsRoute
  PayrollGenerateRoute: typeof PayrollGenerateRoute
  PayrollHistoryRoute: typeof PayrollHistoryRoute
  PayrollLedgerRoute: typeof PayrollLedgerRoute
  PayrollLoansRoute: typeof PayrollLoansRoute
  PayrollPendingRoute: typeof PayrollPendingRoute
  PayrollIndexRoute: typeof PayrollIndexRoute
}

const PayrollRouteChildren: PayrollRouteChildren = {
  PayrollAdvancesRoute: PayrollAdvancesRoute,
  PayrollDeductionsRoute: PayrollDeductionsRoute,
  PayrollGenerateRoute: PayrollGenerateRoute,
  PayrollHistoryRoute: PayrollHistoryRoute,
  PayrollLedgerRoute: PayrollLedgerRoute,
  PayrollLoansRoute: PayrollLoansRoute,
  PayrollPendingRoute: PayrollPendingRoute,
  PayrollIndexRoute: PayrollIndexRoute,
}

const PayrollRouteWithChildren =
  PayrollRoute._addFileChildren(PayrollRouteChildren)

interface SettingsRouteChildren {
  SettingsAttendanceModuleRoute: typeof SettingsAttendanceModuleRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAttendanceModuleRoute: SettingsAttendanceModuleRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  EmployeesRoute: EmployeesRouteWithChildren,
  HomeRoute: HomeRoute,
  HrDashboardRoute: HrDashboardRoute,
  ImportTripsRoute: ImportTripsRoute,
  MastersRoute: MastersRoute,
  OperationsRoute: OperationsRoute,
  PayrollRoute: PayrollRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SystemRoute: SystemRoute,
  UsersRoute: UsersRoute,
  ApiNotifyAdminRoute: ApiNotifyAdminRoute,
  ApiNotifyExpiryRoute: ApiNotifyExpiryRoute,
  ApiNotifyOpenTripsRoute: ApiNotifyOpenTripsRoute,
  ApiDriverThemeRoute: ApiDriverThemeRoute,
  ApiDriverTripsClaimRoute: ApiDriverTripsClaimRoute,
  ApiDriverTripsCurrentRoute: ApiDriverTripsCurrentRoute,
  ApiDriverTripsEndRoute: ApiDriverTripsEndRoute,
  ApiDriverTripsLocationRoute: ApiDriverTripsLocationRoute,
  ApiDriverTripsCheckpointsVerifyRoute: ApiDriverTripsCheckpointsVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
