/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as MastersRouteImport } from './routes/masters'
import { Route as ImportTripsRouteImport } from './routes/import-trips'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiNotifyOpenTripsRouteImport } from './routes/api/notify-open-trips'
import { Route as ApiNotifyExpiryRouteImport } from './routes/api/notify-expiry'
import { Route as ApiNotifyAdminRouteImport } from './routes/api/notify-admin'
import { Route as ApiDriverThemeRouteImport } from './routes/api/driver/theme'
import { Route as ApiDriverTripsLocationRouteImport } from './routes/api/driver/trips/location'
import { Route as ApiDriverTripsEndRouteImport } from './routes/api/driver/trips/end'
import { Route as ApiDriverTripsCurrentRouteImport } from './routes/api/driver/trips/current'
import { Route as ApiDriverTripsClaimRouteImport } from './routes/api/driver/trips/claim'
import { Route as ApiDriverTripsCheckpointsVerifyRouteImport } from './routes/api/driver/trips/checkpoints/verify'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersRoute = MastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportTripsRoute = ImportTripsRouteImport.update({
  id: '/import-trips',
  path: '/import-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyOpenTripsRoute = ApiNotifyOpenTripsRouteImport.update({
  id: '/api/notify-open-trips',
  path: '/api/notify-open-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyExpiryRoute = ApiNotifyExpiryRouteImport.update({
  id: '/api/notify-expiry',
  path: '/api/notify-expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyAdminRoute = ApiNotifyAdminRouteImport.update({
  id: '/api/notify-admin',
  path: '/api/notify-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriverThemeRoute = ApiDriverThemeRouteImport.update({
  id: '/api/driver/theme',
  path: '/api/driver/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriverTripsLocationRoute = ApiDriverTripsLocationRouteImport.update({
  id: '/api/driver/trips/location',
  path: '/api/driver/trips/location',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriverTripsEndRoute = ApiDriverTripsEndRouteImport.update({
  id: '/api/driver/trips/end',
  path: '/api/driver/trips/end',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriverTripsCurrentRoute = ApiDriverTripsCurrentRouteImport.update({
  id: '/api/driver/trips/current',
  path: '/api/driver/trips/current',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriverTripsClaimRoute = ApiDriverTripsClaimRouteImport.update({
  id: '/api/driver/trips/claim',
  path: '/api/driver/trips/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriverTripsCheckpointsVerifyRoute =
  ApiDriverTripsCheckpointsVerifyRouteImport.update({
    id: '/api/driver/trips/checkpoints/verify',
    path: '/api/driver/trips/checkpoints/verify',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/import-trips': typeof ImportTripsRoute
  '/masters': typeof MastersRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/system': typeof SystemRoute
  '/users': typeof UsersRoute
  '/api/notify-admin': typeof ApiNotifyAdminRoute
  '/api/notify-expiry': typeof ApiNotifyExpiryRoute
  '/api/notify-open-trips': typeof ApiNotifyOpenTripsRoute
  '/api/driver/theme': typeof ApiDriverThemeRoute
  '/api/driver/trips/claim': typeof ApiDriverTripsClaimRoute
  '/api/driver/trips/current': typeof ApiDriverTripsCurrentRoute
  '/api/driver/trips/end': typeof ApiDriverTripsEndRoute
  '/api/driver/trips/location': typeof ApiDriverTripsLocationRoute
  '/api/driver/trips/checkpoints/verify': typeof ApiDriverTripsCheckpointsVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/import-trips': typeof ImportTripsRoute
  '/masters': typeof MastersRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/system': typeof SystemRoute
  '/users': typeof UsersRoute
  '/api/notify-admin': typeof ApiNotifyAdminRoute
  '/api/notify-expiry': typeof ApiNotifyExpiryRoute
  '/api/notify-open-trips': typeof ApiNotifyOpenTripsRoute
  '/api/driver/theme': typeof ApiDriverThemeRoute
  '/api/driver/trips/claim': typeof ApiDriverTripsClaimRoute
  '/api/driver/trips/current': typeof ApiDriverTripsCurrentRoute
  '/api/driver/trips/end': typeof ApiDriverTripsEndRoute
  '/api/driver/trips/location': typeof ApiDriverTripsLocationRoute
  '/api/driver/trips/checkpoints/verify': typeof ApiDriverTripsCheckpointsVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/import-trips': typeof ImportTripsRoute
  '/masters': typeof MastersRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/system': typeof SystemRoute
  '/users': typeof UsersRoute
  '/api/notify-admin': typeof ApiNotifyAdminRoute
  '/api/notify-expiry': typeof ApiNotifyExpiryRoute
  '/api/notify-open-trips': typeof ApiNotifyOpenTripsRoute
  '/api/driver/theme': typeof ApiDriverThemeRoute
  '/api/driver/trips/claim': typeof ApiDriverTripsClaimRoute
  '/api/driver/trips/current': typeof ApiDriverTripsCurrentRoute
  '/api/driver/trips/end': typeof ApiDriverTripsEndRoute
  '/api/driver/trips/location': typeof ApiDriverTripsLocationRoute
  '/api/driver/trips/checkpoints/verify': typeof ApiDriverTripsCheckpointsVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/home'
    | '/import-trips'
    | '/masters'
    | '/operations'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
    | '/system'
    | '/users'
    | '/api/notify-admin'
    | '/api/notify-expiry'
    | '/api/notify-open-trips'
    | '/api/driver/theme'
    | '/api/driver/trips/claim'
    | '/api/driver/trips/current'
    | '/api/driver/trips/end'
    | '/api/driver/trips/location'
    | '/api/driver/trips/checkpoints/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/home'
    | '/import-trips'
    | '/masters'
    | '/operations'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
    | '/system'
    | '/users'
    | '/api/notify-admin'
    | '/api/notify-expiry'
    | '/api/notify-open-trips'
    | '/api/driver/theme'
    | '/api/driver/trips/claim'
    | '/api/driver/trips/current'
    | '/api/driver/trips/end'
    | '/api/driver/trips/location'
    | '/api/driver/trips/checkpoints/verify'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/home'
    | '/import-trips'
    | '/masters'
    | '/operations'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
    | '/system'
    | '/users'
    | '/api/notify-admin'
    | '/api/notify-expiry'
    | '/api/notify-open-trips'
    | '/api/driver/theme'
    | '/api/driver/trips/claim'
    | '/api/driver/trips/current'
    | '/api/driver/trips/end'
    | '/api/driver/trips/location'
    | '/api/driver/trips/checkpoints/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HomeRoute: typeof HomeRoute
  ImportTripsRoute: typeof ImportTripsRoute
  MastersRoute: typeof MastersRoute
  OperationsRoute: typeof OperationsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SystemRoute: typeof SystemRoute
  UsersRoute: typeof UsersRoute
  ApiNotifyAdminRoute: typeof ApiNotifyAdminRoute
  ApiNotifyExpiryRoute: typeof ApiNotifyExpiryRoute
  ApiNotifyOpenTripsRoute: typeof ApiNotifyOpenTripsRoute
  ApiDriverThemeRoute: typeof ApiDriverThemeRoute
  ApiDriverTripsClaimRoute: typeof ApiDriverTripsClaimRoute
  ApiDriverTripsCurrentRoute: typeof ApiDriverTripsCurrentRoute
  ApiDriverTripsEndRoute: typeof ApiDriverTripsEndRoute
  ApiDriverTripsLocationRoute: typeof ApiDriverTripsLocationRoute
  ApiDriverTripsCheckpointsVerifyRoute: typeof ApiDriverTripsCheckpointsVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters': {
      id: '/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof MastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-trips': {
      id: '/import-trips'
      path: '/import-trips'
      fullPath: '/import-trips'
      preLoaderRoute: typeof ImportTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-open-trips': {
      id: '/api/notify-open-trips'
      path: '/api/notify-open-trips'
      fullPath: '/api/notify-open-trips'
      preLoaderRoute: typeof ApiNotifyOpenTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-expiry': {
      id: '/api/notify-expiry'
      path: '/api/notify-expiry'
      fullPath: '/api/notify-expiry'
      preLoaderRoute: typeof ApiNotifyExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-admin': {
      id: '/api/notify-admin'
      path: '/api/notify-admin'
      fullPath: '/api/notify-admin'
      preLoaderRoute: typeof ApiNotifyAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/driver/theme': {
      id: '/api/driver/theme'
      path: '/api/driver/theme'
      fullPath: '/api/driver/theme'
      preLoaderRoute: typeof ApiDriverThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/driver/trips/location': {
      id: '/api/driver/trips/location'
      path: '/api/driver/trips/location'
      fullPath: '/api/driver/trips/location'
      preLoaderRoute: typeof ApiDriverTripsLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/driver/trips/end': {
      id: '/api/driver/trips/end'
      path: '/api/driver/trips/end'
      fullPath: '/api/driver/trips/end'
      preLoaderRoute: typeof ApiDriverTripsEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/driver/trips/current': {
      id: '/api/driver/trips/current'
      path: '/api/driver/trips/current'
      fullPath: '/api/driver/trips/current'
      preLoaderRoute: typeof ApiDriverTripsCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/driver/trips/claim': {
      id: '/api/driver/trips/claim'
      path: '/api/driver/trips/claim'
      fullPath: '/api/driver/trips/claim'
      preLoaderRoute: typeof ApiDriverTripsClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/driver/trips/checkpoints/verify': {
      id: '/api/driver/trips/checkpoints/verify'
      path: '/api/driver/trips/checkpoints/verify'
      fullPath: '/api/driver/trips/checkpoints/verify'
      preLoaderRoute: typeof ApiDriverTripsCheckpointsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HomeRoute: HomeRoute,
  ImportTripsRoute: ImportTripsRoute,
  MastersRoute: MastersRoute,
  OperationsRoute: OperationsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SystemRoute: SystemRoute,
  UsersRoute: UsersRoute,
  ApiNotifyAdminRoute: ApiNotifyAdminRoute,
  ApiNotifyExpiryRoute: ApiNotifyExpiryRoute,
  ApiNotifyOpenTripsRoute: ApiNotifyOpenTripsRoute,
  ApiDriverThemeRoute: ApiDriverThemeRoute,
  ApiDriverTripsClaimRoute: ApiDriverTripsClaimRoute,
  ApiDriverTripsCurrentRoute: ApiDriverTripsCurrentRoute,
  ApiDriverTripsEndRoute: ApiDriverTripsEndRoute,
  ApiDriverTripsLocationRoute: ApiDriverTripsLocationRoute,
  ApiDriverTripsCheckpointsVerifyRoute: ApiDriverTripsCheckpointsVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
