-- Driver's App support for OWN-VEHICLE trips only.
-- Apply this file manually in Supabase SQL Editor before using the web controls.

create extension if not exists pgcrypto;

create table if not exists public.driver_trip_qr_tokens (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references public.trips(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists driver_trip_qr_tokens_trip_idx
  on public.driver_trip_qr_tokens (trip_id, expires_at desc);

create table if not exists public.driver_trip_links (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references public.trips(id) on delete cascade,
  device_id text not null,
  session_token_hash text not null unique,
  linked_at timestamptz not null default now(),
  last_seen_at timestamptz,
  ended_at timestamptz
);

create unique index if not exists driver_trip_links_one_active_device_idx
  on public.driver_trip_links (trip_id)
  where ended_at is null;

create index if not exists driver_trip_links_trip_idx
  on public.driver_trip_links (trip_id, ended_at, last_seen_at desc);

create table if not exists public.driver_trip_locations (
  id bigint generated by default as identity primary key,
  link_id uuid not null references public.driver_trip_links(id) on delete cascade,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  accuracy_m double precision check (accuracy_m is null or accuracy_m >= 0),
  recorded_at timestamptz not null default now()
);

create index if not exists driver_trip_locations_link_time_idx
  on public.driver_trip_locations (link_id, recorded_at desc);

-- These tables are accessed through security-definer functions only.
alter table public.driver_trip_qr_tokens enable row level security;
alter table public.driver_trip_links enable row level security;
alter table public.driver_trip_locations enable row level security;

revoke all on public.driver_trip_qr_tokens from anon, authenticated;
revoke all on public.driver_trip_links from anon, authenticated;
revoke all on public.driver_trip_locations from anon, authenticated;
grant all on public.driver_trip_qr_tokens to service_role;
grant all on public.driver_trip_links to service_role;
grant all on public.driver_trip_locations to service_role;
grant usage, select on sequence public.driver_trip_locations_id_seq to service_role;

drop function if exists public.issue_driver_trip_qr(uuid, integer);
create or replace function public.issue_driver_trip_qr(
  p_trip_id uuid,
  p_ttl_minutes integer default 30
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_trip record;
  v_token text;
  v_expires_at timestamptz;
begin
  if p_ttl_minutes < 1 or p_ttl_minutes > 1440 then
    raise exception 'QR expiry must be between 1 and 1440 minutes';
  end if;

  select t.id, t.trip_code, t.ownership
    into v_trip
    from public.trips t
   where t.id = p_trip_id
     and t.ownership = 'own';

  if not found then
    raise exception 'Only own-vehicle trips can be linked to the Driver''s App';
  end if;

  v_token := encode(gen_random_bytes(32), 'hex');
  v_expires_at := now() + make_interval(mins => p_ttl_minutes);

  insert into public.driver_trip_qr_tokens (trip_id, token_hash, expires_at)
  values (v_trip.id, encode(digest(v_token, 'sha256'), 'hex'), v_expires_at);

  return jsonb_build_object(
    'token', v_token,
    'trip_id', v_trip.id,
    'trip_code', v_trip.trip_code,
    'expires_at', v_expires_at
  );
end;
$$;

drop function if exists public.claim_driver_trip(text, text);
create or replace function public.claim_driver_trip(
  p_qr_token text,
  p_device_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_qr record;
  v_link record;
  v_session_token text;
  v_link_id uuid;
begin
  if coalesce(trim(p_qr_token), '') = '' or coalesce(trim(p_device_id), '') = '' then
    raise exception 'QR token and device ID are required';
  end if;

  select q.id, q.trip_id, t.trip_code, t.ownership, q.expires_at, q.used_at
    into v_qr
    from public.driver_trip_qr_tokens q
    join public.trips t on t.id = q.trip_id
   where q.token_hash = encode(digest(p_qr_token, 'sha256'), 'hex')
   for update;

  if not found or v_qr.ownership <> 'own' then
    raise exception 'Invalid own-vehicle trip QR code';
  end if;
  if v_qr.expires_at <= now() or v_qr.used_at is not null then
    raise exception 'This trip QR code has expired or was already used';
  end if;

  select l.id, l.device_id, l.ended_at
    into v_link
    from public.driver_trip_links l
   where l.trip_id = v_qr.trip_id
     and l.ended_at is null
   for update;

  if found and v_link.device_id <> p_device_id then
    return jsonb_build_object(
      'status', 'already_linked',
      'trip_code', v_qr.trip_code
    );
  end if;

  v_session_token := encode(gen_random_bytes(32), 'hex');

  if found then
    v_link_id := v_link.id;
    update public.driver_trip_links
       set session_token_hash = encode(digest(v_session_token, 'sha256'), 'hex'),
           last_seen_at = now()
     where id = v_link_id;
  else
    insert into public.driver_trip_links (trip_id, device_id, session_token_hash, last_seen_at)
    values (v_qr.trip_id, p_device_id, encode(digest(v_session_token, 'sha256'), 'hex'), now())
    returning id into v_link_id;
  end if;

  update public.driver_trip_qr_tokens
     set used_at = now()
   where id = v_qr.id;

  return jsonb_build_object(
    'status', 'linked',
    'session_token', v_session_token,
    'trip_id', v_qr.trip_id,
    'trip_code', v_qr.trip_code
  );
exception
  when unique_violation then
    return jsonb_build_object(
      'status', 'already_linked',
      'message', 'Another device connected to this trip first'
    );
end;
$$;

drop function if exists public.get_driver_trip(text);
create or replace function public.get_driver_trip(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_trip record;
  v_trip_id uuid;
  v_link_id uuid;
  v_manifests jsonb;
  v_latest_location jsonb;
begin
  select l.id, l.trip_id
    into v_link_id, v_trip_id
    from public.driver_trip_links l
   where l.session_token_hash = encode(digest(p_session_token, 'sha256'), 'hex')
     and l.ended_at is null
   for update;

  if not found then raise exception 'Driver session is not active'; end if;

  select t.id, t.trip_code, t.start_date, t.start_time, t.ownership,
         t.vehicle_id, t.driver_id, t.start_location_id, t.end_location_id,
         v.registration_number, v.internal_code, v.nickname, v.manufacturer, v.model,
         d.driver_code, d.full_name, d.mobile_number,
         sl.location_name as source_name, sl.city as source_city, sl.state as source_state,
         el.location_name as destination_name, el.city as destination_city, el.state as destination_state
    into v_trip
    from public.trips t
    left join public.vehicles v on v.id = t.vehicle_id
    left join public.drivers d on d.id = t.driver_id
    left join public.locations sl on sl.id = t.start_location_id
    left join public.locations el on el.id = t.end_location_id
   where t.id = v_trip_id
     and t.ownership = 'own';

  select coalesce(jsonb_agg(jsonb_build_object(
    'manifest_number', m.manifest_number,
    'from_pin_code', m.from_pin_code,
    'to_pin_code', m.to_pin_code,
    'weight_kg', m.weight_kg,
    'quantity', m.quantity,
    'source_name', fl.location_name,
    'destination_name', tl.location_name
  ) order by m.created_at), '[]'::jsonb)
    into v_manifests
    from public.trip_manifests m
    left join public.locations fl on fl.id = m.from_location_id
    left join public.locations tl on tl.id = m.to_location_id
   where m.trip_id = v_trip_id;

  select jsonb_build_object(
    'latitude', x.latitude,
    'longitude', x.longitude,
    'accuracy_m', x.accuracy_m,
    'recorded_at', x.recorded_at
  ) into v_latest_location
    from public.driver_trip_locations x
   where x.link_id = v_link_id
   order by x.recorded_at desc
   limit 1;

  update public.driver_trip_links set last_seen_at = now() where id = v_link_id;

  return jsonb_build_object(
    'trip', jsonb_build_object(
      'id', v_trip_id,
      'trip_code', v_trip.trip_code,
      'start_date', v_trip.start_date,
      'start_time', v_trip.start_time,
      'source', jsonb_build_object('name', v_trip.source_name, 'city', v_trip.source_city, 'state', v_trip.source_state),
      'destination', jsonb_build_object('name', v_trip.destination_name, 'city', v_trip.destination_city, 'state', v_trip.destination_state),
      'vehicle', jsonb_build_object('registration_number', v_trip.registration_number, 'internal_code', v_trip.internal_code, 'nickname', v_trip.nickname, 'manufacturer', v_trip.manufacturer, 'model', v_trip.model),
      'driver', jsonb_build_object('code', v_trip.driver_code, 'name', v_trip.full_name, 'mobile_number', v_trip.mobile_number),
      'manifests', v_manifests
    ),
    'latest_location', coalesce(v_latest_location, 'null'::jsonb)
  );
end;
$$;

drop function if exists public.record_driver_location(text, double precision, double precision, double precision);
create or replace function public.record_driver_location(
  p_session_token text,
  p_latitude double precision,
  p_longitude double precision,
  p_accuracy_m double precision default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_link_id uuid;
begin
  select id into v_link_id
    from public.driver_trip_links
   where session_token_hash = encode(digest(p_session_token, 'sha256'), 'hex')
     and ended_at is null;
  if not found then raise exception 'Driver session is not active'; end if;

  insert into public.driver_trip_locations (link_id, latitude, longitude, accuracy_m)
  values (v_link_id, p_latitude, p_longitude, p_accuracy_m);
  update public.driver_trip_links set last_seen_at = now() where id = v_link_id;
  return jsonb_build_object('ok', true);
end;
$$;

drop function if exists public.end_driver_trip(text);
create or replace function public.end_driver_trip(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_link_id uuid;
begin
  update public.driver_trip_links
     set ended_at = now(), last_seen_at = now()
   where session_token_hash = encode(digest(p_session_token, 'sha256'), 'hex')
     and ended_at is null
   returning id into v_link_id;
  if not found then raise exception 'Driver session is not active'; end if;
  return jsonb_build_object('ok', true, 'ended_at', now());
end;
$$;

drop function if exists public.get_trip_live_location(uuid);
create or replace function public.get_trip_live_location(p_trip_id uuid)
returns jsonb
language sql
security definer
set search_path = public, extensions
as $$
  select case when t.ownership = 'own' then (
    select jsonb_build_object(
      'trip_id', t.id,
      'trip_code', t.trip_code,
      'latitude', x.latitude,
      'longitude', x.longitude,
      'accuracy_m', x.accuracy_m,
      'recorded_at', x.recorded_at,
      'last_seen_at', l.last_seen_at,
      'active', (l.ended_at is null)
    )
    from public.driver_trip_links l
    join public.driver_trip_locations x on x.link_id = l.id
    where l.trip_id = t.id
    order by x.recorded_at desc
    limit 1
  ) else null end
  from public.trips t
  where t.id = p_trip_id;
$$;

grant execute on function public.issue_driver_trip_qr(uuid, integer) to anon, authenticated;
grant execute on function public.claim_driver_trip(text, text) to anon, authenticated;
grant execute on function public.get_driver_trip(text) to anon, authenticated;
grant execute on function public.record_driver_location(text, double precision, double precision, double precision) to anon, authenticated;
grant execute on function public.end_driver_trip(text) to anon, authenticated;
grant execute on function public.get_trip_live_location(uuid) to anon, authenticated;

revoke all on function public.issue_driver_trip_qr(uuid, integer) from public;
revoke all on function public.claim_driver_trip(text, text) from public;
revoke all on function public.get_driver_trip(text) from public;
revoke all on function public.record_driver_location(text, double precision, double precision, double precision) from public;
revoke all on function public.end_driver_trip(text) from public;
revoke all on function public.get_trip_live_location(uuid) from public;

-- Recommended hardening after validating the app:
-- Replace anon grants on issue_driver_trip_qr/get_trip_live_location with authenticated grants
-- if the web app is configured to require Supabase auth for all dashboard users.

alter table public.driver_trip_qr_tokens force row level security;
alter table public.driver_trip_links force row level security;
alter table public.driver_trip_locations force row level security;

-- End of migration.
