-- Access Levels — safe, idempotent Supabase setup
-- Run once in the Supabase SQL Editor. Existing app_users and access are preserved.
begin;

-- The UI calls the existing `viewer` role "Manager". Keep the stored value so
-- existing accounts and signed sessions remain compatible.
do $$
declare constraint_name text;
begin
  select conname into constraint_name
  from pg_constraint
  where conrelid = 'public.app_users'::regclass and contype = 'c'
    and pg_get_constraintdef(oid) ilike '%role%';
  if constraint_name is not null then
    execute format('alter table public.app_users drop constraint %I', constraint_name);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'app_users_role_check' and conrelid = 'public.app_users'::regclass) then
    alter table public.app_users add constraint app_users_role_check check (role in ('admin', 'viewer', 'basic'));
  end if;
end $$;

create table if not exists public.access_scopes (
  scope_key text primary key,
  module text not null,
  label text not null,
  description text not null default '',
  branch_aware boolean not null default false,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.role_permissions (
  role text not null check (role in ('admin', 'viewer', 'basic')),
  scope_key text not null references public.access_scopes(scope_key) on update cascade on delete cascade,
  action text not null check (action in ('read','create','update','delete','approve','close','reopen','import','export','manage')),
  allowed boolean not null default false,
  branch_mode text not null default 'none' check (branch_mode in ('all','assigned','none')),
  updated_by uuid references public.app_users(id) on delete set null,
  updated_at timestamptz not null default now(),
  primary key (role, scope_key, action)
);

create table if not exists public.user_permission_overrides (
  user_id uuid not null references public.app_users(id) on delete cascade,
  scope_key text not null references public.access_scopes(scope_key) on update cascade on delete cascade,
  action text not null check (action in ('read','create','update','delete','approve','close','reopen','import','export','manage')),
  effect text not null check (effect in ('allow','deny')),
  branch_mode text not null default 'none' check (branch_mode in ('all','assigned','none')),
  updated_by uuid references public.app_users(id) on delete set null,
  updated_at timestamptz not null default now(),
  primary key (user_id, scope_key, action)
);

create table if not exists public.user_scope_branches (
  user_id uuid not null references public.app_users(id) on delete cascade,
  scope_key text not null references public.access_scopes(scope_key) on update cascade on delete cascade,
  branch_id uuid not null references public.branches(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, scope_key, branch_id)
);

create table if not exists public.permission_change_logs (
  id bigint generated by default as identity primary key,
  changed_by uuid references public.app_users(id) on delete set null,
  target_role text check (target_role in ('admin', 'viewer', 'basic')),
  target_user_id uuid references public.app_users(id) on delete set null,
  scope_key text not null,
  action text not null,
  allowed boolean not null,
  branch_mode text not null,
  created_at timestamptz not null default now()
);

-- These security-control tables are service-role only. The application updates
-- them through HMAC-token-verified server functions; never from the browser.
alter table public.access_scopes enable row level security;
alter table public.role_permissions enable row level security;
alter table public.user_permission_overrides enable row level security;
alter table public.user_scope_branches enable row level security;
alter table public.permission_change_logs enable row level security;
grant all on public.access_scopes, public.role_permissions, public.user_permission_overrides,
  public.user_scope_branches, public.permission_change_logs to service_role;
revoke all on public.access_scopes, public.role_permissions, public.user_permission_overrides,
  public.user_scope_branches, public.permission_change_logs from anon, authenticated;

insert into public.access_scopes (scope_key,module,label,description,branch_aware,sort_order) values
('operations.monthly_mis','Operations','Monthly MIS','Monthly branch compliance forms',true,10),
('operations.trips','Operations','Trips','Trips, manifests, income and expenses',true,20),
('operations.income','Operations','Other Income','Branch-wise other income',true,30),
('operations.expenditure','Operations','Expenditure','Branch-wise operational spending',true,40),
('operations.driver_payroll','Operations','Driver Payroll','Driver salary, advances and deductions',true,50),
('operations.fixed_income','Operations','Fixed Income','Recurring contract charges',true,60),
('operations.trip_averages','Operations','Trip Averages','Monthly distribution analysis',true,70),
('operations.emi','Operations','EMI Scheduler','Vehicle loan and EMI tracker',true,80),
('operations.yearly_expenses','Operations','Yearly Expenses','Fixed yearly cost tracker',true,90),
('operations.import','Operations','Import Trips','Bulk historical trip import',true,100),
('masters.vehicles','Masters','Vehicles','Fleet and specifications',true,110),
('masters.drivers','Masters','Drivers','Driver records and documents',true,120),
('masters.transporters','Masters','Transporters','Owners and brokers',true,130),
('masters.locations','Masters','Locations','Pickup and drop locations',false,140),
('masters.sources','Masters','Sources / Contracts','Contract rates and slabs',true,150),
('hr.employees','HRMS','Employees','Employee profiles and hierarchy',true,160),
('hr.departments','HRMS','Departments','Departments and positions',false,170),
('hr.attendance','HRMS','Attendance','Marking and attendance history',true,180),
('hr.holidays','HRMS','Holidays','Holiday calendar',false,190),
('hr.payroll','HRMS','Payroll','Salary generation, loans and deductions',true,200),
('dashboard.tms','Dashboards','TMS Dashboard','Profit, revenue and fleet analytics',true,210),
('dashboard.hr','Dashboards','HR Dashboard','Employee, attendance and payroll analytics',true,220),
('reports.booking','Reports','Booking Report','Branch booking and expense reporting',true,230),
('reports.financial','Reports','Financial Reports','P&L and expense ledgers',true,240),
('reports.compliance','Reports','Compliance Reports','Insurance, road tax and MIS reports',true,250),
('administration.users','Administration','Users','Accounts, roles and branch assignments',false,260),
('administration.devices','Administration','Devices','Passkey device approvals and assignments',false,270),
('administration.logs','Administration','Activity Logs','Application audit history',false,280),
('settings.company','Settings','Company','Company profile',false,290),
('settings.branches','Settings','Branches','Branch configuration',false,300),
('settings.appearance','Settings','Appearance','Theme and login appearance',false,310),
('settings.passkeys','Settings','Passkey Security','Universal device protection',false,320),
('settings.access_levels','Settings','Access Levels','Role permission matrix',false,330),
('system.health','System','System Health','Project, database and security health',false,340),
('system.corrections','System','Data Corrections','Repair and correction operations',false,350),
('notifications','System','Notifications','Operational alerts',true,360),
('assistant','System','ORCA AI','AI assistant and actions',true,370)
on conflict (scope_key) do update set module=excluded.module,label=excluded.label,
 description=excluded.description,branch_aware=excluded.branch_aware,sort_order=excluded.sort_order;

-- Seed only missing rows. Re-running this script never overwrites an admin's choices.
with actions(action) as (values ('read'),('create'),('update'),('delete'),('approve'),('close'),('reopen'),('import'),('export'),('manage')),
roles(role) as (values ('admin'),('viewer'),('basic'))
insert into public.role_permissions(role,scope_key,action,allowed,branch_mode)
select r.role, s.scope_key, a.action,
  case
    when r.role='admin' then true
    when r.role='viewer' then a.action in ('read','export') and (
      s.scope_key like 'operations.%' and s.scope_key not in ('operations.monthly_mis','operations.import')
      or s.scope_key in ('masters.vehicles','masters.drivers','masters.transporters','masters.locations')
      or s.scope_key like 'hr.%' or s.scope_key like 'dashboard.%' or s.scope_key like 'reports.%'
      or s.scope_key='notifications')
    when r.role='basic' then s.scope_key in (
      'operations.monthly_mis','operations.trips','operations.income','operations.expenditure',
      'operations.driver_payroll','reports.booking','masters.drivers','masters.transporters')
  end,
  case when not s.branch_aware then 'none' when r.role='basic' then 'assigned' else 'all' end
from roles r cross join public.access_scopes s cross join actions a
on conflict (role,scope_key,action) do nothing;

create index if not exists role_permissions_scope_idx on public.role_permissions(scope_key);
create index if not exists user_permission_overrides_user_idx on public.user_permission_overrides(user_id);
create index if not exists user_scope_branches_user_idx on public.user_scope_branches(user_id);
create index if not exists permission_change_logs_created_idx on public.permission_change_logs(created_at desc);

commit;
